<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getLogfiles</value>
  <array name="sig" type="value" depth="1">
    <value>[o] field:0:required logfolder</value>
    <value>[o] record:1:required logfiles</value>
    <value>[o] - field:0:required filename</value>
    <value>[o] - field:0:required absolutePath</value>
    <value>[o] - field:0:required relativePath</value>
    <value>[o] - field:0:required size</value>
    <value>[o] - field:0:required modificationDate</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CQ0KRmlsZSBsb2dEaXIgPSBnZXRMb2dzRm9sZGVyKCk7DQoNCkFycmF5TGlzdDxJRGF0YT4gZmls
ZXMgPSBuZXcgQXJyYXlMaXN0PElEYXRhPigpOw0KU2ltcGxlRGF0ZUZvcm1hdCBzZGYgPSBuZXcg
U2ltcGxlRGF0ZUZvcm1hdCgiZGQuTU0ueXl5eSBISDptbTpzcyIpOw0KU2ltcGxlRGF0ZUZvcm1h
dCBzb3J0U2RmID0gbmV3IFNpbXBsZURhdGVGb3JtYXQoInl5eXlNTWRkSEhtbXNzIik7DQpEZWNp
bWFsRm9ybWF0IGRmID0gbmV3IERlY2ltYWxGb3JtYXQoIjAwMDAwMDAwMCIpOw0KDQpJT0ZpbGVG
aWx0ZXIgZmYgPSBuZXcgQWdlRmlsZUZpbHRlcihTeXN0ZW0uY3VycmVudFRpbWVNaWxsaXMoKSAt
IDMwTCAqIDg0NjAwICogIDEwMDAsIGZhbHNlKTsNCkNvbGxlY3Rpb248RmlsZT4gbG9nZmlsZXMg
PSBGaWxlVXRpbHMubGlzdEZpbGVzKGxvZ0RpciwgZmYsIFRydWVGaWxlRmlsdGVyLklOU1RBTkNF
KTsNCmZvciAoRmlsZSBsb2dmaWxlIDogbG9nZmlsZXMpIHsNCglpZiAoIWxvZ2ZpbGUuZ2V0QWJz
b2x1dGVQYXRoKCkuY29udGFpbnMoIld4Q29uZmlnIikgfHwgIWxvZ2ZpbGUuZ2V0QWJzb2x1dGVQ
YXRoKCkuY29udGFpbnMoImF1ZGl0IikpIHsNCgkJSURhdGEgaUxvZ2ZpbGUgPSBJRGF0YUZhY3Rv
cnkuY3JlYXRlKCk7DQoJCUlEYXRhQ3Vyc29yIGxvZ2ZpbGVDdXJzb3IgPSBpTG9nZmlsZS5nZXRD
dXJzb3IoKTsNCgkJSURhdGFVdGlsLnB1dChsb2dmaWxlQ3Vyc29yLCAiZmlsZW5hbWUiLCBsb2dm
aWxlLmdldE5hbWUoKSk7DQoJCUlEYXRhVXRpbC5wdXQobG9nZmlsZUN1cnNvciwgImFic29sdXRl
UGF0aCIsIGxvZ2ZpbGUuZ2V0QWJzb2x1dGVQYXRoKCkpOw0KCQkNCgkJU3RyaW5nIHJlbFBhdGgg
PSBsb2dmaWxlLmdldEFic29sdXRlUGF0aCgpLnN1YnN0cmluZyhsb2dEaXIuZ2V0QWJzb2x1dGVQ
YXRoKCkubGVuZ3RoKCkpOw0KCQlJRGF0YVV0aWwucHV0KGxvZ2ZpbGVDdXJzb3IsICJyZWxhdGl2
ZVBhdGgiLCByZWxQYXRoKTsNCgkJDQoJCUlEYXRhVXRpbC5wdXQobG9nZmlsZUN1cnNvciwgInNp
emUiLCBGaWxlVXRpbHMuYnl0ZUNvdW50VG9EaXNwbGF5U2l6ZShsb2dmaWxlLmxlbmd0aCgpKSk7
DQoJCUlEYXRhVXRpbC5wdXQobG9nZmlsZUN1cnNvciwgInNvcnRTaXplIiwgZGYuZm9ybWF0KGxv
Z2ZpbGUubGVuZ3RoKCkpKTsNCgkJSURhdGFVdGlsLnB1dChsb2dmaWxlQ3Vyc29yLCAibW9kaWZp
Y2F0aW9uRGF0ZSIsIHNkZi5mb3JtYXQobG9nZmlsZS5sYXN0TW9kaWZpZWQoKSkpOw0KCQlJRGF0
YVV0aWwucHV0KGxvZ2ZpbGVDdXJzb3IsICJzb3J0TW9kaWZpY2F0aW9uRGF0ZSIsIHNvcnRTZGYu
Zm9ybWF0KGxvZ2ZpbGUubGFzdE1vZGlmaWVkKCkpKTsNCgkJDQoJCWxvZ2ZpbGVDdXJzb3IuZGVz
dHJveSgpOw0KCQlmaWxlcy5hZGQoaUxvZ2ZpbGUpOw0KCX0NCn0NCg0KSURhdGFDdXJzb3IgcGlw
ZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCklEYXRhVXRpbC5wdXQocGlwZWxp
bmVDdXJzb3IsICJsb2dmb2xkZXIiLCBsb2dEaXIuZ2V0QWJzb2x1dGVQYXRoKCkpOw0KSURhdGFV
dGlsLnB1dChwaXBlbGluZUN1cnNvciwgImZvbGRlclNpemUiLCBGaWxlVXRpbHMuYnl0ZUNvdW50
VG9EaXNwbGF5U2l6ZShGaWxlVXRpbHMuc2l6ZU9mRGlyZWN0b3J5KGxvZ0RpcikpKTsNCg0KSURh
dGFbXSBsb2dmaWxlc0FycmF5ID0gbmV3IElEYXRhW2ZpbGVzLnNpemUoKV07DQpmaWxlcy50b0Fy
cmF5KGxvZ2ZpbGVzQXJyYXkpOw0KSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgImxvZ2Zp
bGVzIiwgbG9nZmlsZXNBcnJheSk7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQoJDQoJDQoJ
DQoJDQo=</value>
</Values>
