<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">cleanupConstantlyTailing</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required longPollingIntervalInSeconds</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFNYXAgcGlwZU1hcCA9IG5ldyBJRGF0YU1hcChwaXBlbGluZSk7DQppbnQgbG9uZ1BvbGxp
bmdJbnRlcnZhbEluU2Vjb25kcyA9IEludGVnZXIudmFsdWVPZihwaXBlTWFwLmdldEFzU3RyaW5n
KCJsb25nUG9sbGluZ0ludGVydmFsSW5TZWNvbmRzIikpOw0KDQpTZXQ8RW50cnk8U3RyaW5nLCBP
cGVuUmVhZGVyPj4gb3BlblJlYWRlcnMgPSBvcGVuUmVhZGVyTWFwLmVudHJ5U2V0KCk7DQpsb25n
IGN1cnJlbnREYXRlID0gU3lzdGVtLmN1cnJlbnRUaW1lTWlsbGlzKCk7DQoNCmZvciAoRW50cnk8
U3RyaW5nLCBPcGVuUmVhZGVyPiBlbnRyeSA6IG9wZW5SZWFkZXJzKSB7DQoJT3BlblJlYWRlciBv
cGVuUmVhZGVyID0gZW50cnkuZ2V0VmFsdWUoKTsNCg0KCWlmIChvcGVuUmVhZGVyLmxhc3RNb2Rp
ZmllZC5nZXRUaW1lKCkgPCBjdXJyZW50RGF0ZSAtIGxvbmdQb2xsaW5nSW50ZXJ2YWxJblNlY29u
ZHMgKiAxMDAwICogMikgew0KCQl0cnkgew0KCQkJZGVidWdMb2dJbmZvKCJDbG9zZSBjb25zdGFu
dGx5VGFpbGluZyBmb3IgIiArIG9wZW5SZWFkZXIuZmlsZS5nZXROYW1lKCkpOw0KCQkJb3BlblJl
YWRlck1hcC5yZW1vdmUoZW50cnkuZ2V0S2V5KCkpOw0KCQkJb3BlblJlYWRlci5idWZmZXJlZFJl
YWRlci5jbG9zZSgpOw0KCQl9IGNhdGNoIChJT0V4Y2VwdGlvbiBlKSB7DQoJCQlkZWJ1Z0xvZ0Vy
cm9yKGUuZ2V0TG9jYWxpemVkTWVzc2FnZSgpKTsNCgkJfQ0KCX0NCn0NCgkNCg==</value>
</Values>
