<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getFileContent</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required filename</value>
    <value>[o] field:0:required content</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CQkvLyBUaGlzIHNlcnZpY2UgZ2V0IHRoZSBjb250ZW50IG9mIGEgZmlsZSBpbiBTdHJpbmcNCgkJ
Ly8NCgkJLy8gSW5wdXQ6IAlmaWxlbmFtZToJbmFtZSBvZiB0aGUgZmlsZSB5b3Ugd2FudCB0byB3
cml0ZQ0KCQkvLyBPdXRwdXQ6CWNvbnRlbnQ6CWNvbnRlbnQgb2YgZmlsZSBpbiBzdHJpbmcNCgkJ
Ly8NCgkJLy8gKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKg0KCQkNCgkJSURhdGFDdXJzb3IgaWRjID0gcGlw
ZWxpbmUuZ2V0Q3Vyc29yKCk7ICANCgkJU3RyaW5nIGZpbGVuYW1lID0gSURhdGFVdGlsLmdldFN0
cmluZyhpZGMsICJmaWxlbmFtZSIpOyAgDQoJCWlmIChmaWxlbmFtZSA9PSBudWxsKSB7DQoJCQlm
aWxlbmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoaWRjLCAiZmlsZU5hbWUiKTsNCgkJCWlmIChm
aWxlbmFtZSA9PSBudWxsKSB7DQoJCQkJdGhyb3cgbmV3IE51bGxQb2ludGVyRXhjZXB0aW9uKCJN
aXNzaW5nIHBhcmFtZXRlcjogZmlsZW5hbWUiKTsNCgkJCX0NCgkJfQ0KCQ0KCQl0cnkgeyAgDQoJ
CQlqYXZhLmlvLkZpbGUgZmlsZSA9IG5ldyBqYXZhLmlvLkZpbGUoZmlsZW5hbWUpOw0KCQkJU3Ry
aW5nQnVmZmVyIGNvbnRlbnRzID0gbmV3IFN0cmluZ0J1ZmZlcigpOw0KCQkJQnVmZmVyZWRSZWFk
ZXIgaW5wdXQgPSAgbmV3IEJ1ZmZlcmVkUmVhZGVyKG5ldyBGaWxlUmVhZGVyKGZpbGUpKTsNCgkJ
CQ0KCQkJdHJ5IHsNCgkJCQlTdHJpbmcgbGluZSA9IG51bGw7IA0KCQkJICAgICAgICB3aGlsZSAo
KCBsaW5lID0gaW5wdXQucmVhZExpbmUoKSkgIT0gbnVsbCl7DQoJCQkgICAgICAgIAljb250ZW50
cy5hcHBlbmQobGluZSk7DQoJCQkgICAgICAgIAljb250ZW50cy5hcHBlbmQoU3lzdGVtLmdldFBy
b3BlcnR5KCJsaW5lLnNlcGFyYXRvciIpKTsNCgkJCSAgICAgICAgfQ0KCQkJfSBjYXRjaCAoSU9F
eGNlcHRpb24gZSkgeyAgDQoJCQkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZS5nZXRNZXNz
YWdlKCkpOyAgDQoJCQl9IGZpbmFsbHkgew0KCQkJCWlucHV0LmNsb3NlKCk7DQoJCQl9DQoJCQlp
ZGMuaW5zZXJ0QWZ0ZXIoImNvbnRlbnQiLCBjb250ZW50cy50b1N0cmluZygpKTsNCgkJfSBjYXRj
aCAoRXhjZXB0aW9uIGUpIHsgIA0KCQkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZS5nZXRN
ZXNzYWdlKCkpOyAgDQoJCX0gZmluYWxseSB7DQoJCQlpZGMuZGVzdHJveSgpOwkJCQ0KCQl9DQoJ
DQo=</value>
</Values>
